#include "param_registry.h"
#include "modulation_engine.h"
#include "config/effect_config.h"
#include "ui/ui_units.h"
#include <string.h>

typedef struct ParamEntry {
    const char* id;
    ParamDef def;
} ParamEntry;

static const ParamEntry PARAM_TABLE[] = {
    {"physarum.sensorDistance", {1.0f, 100.0f}},
    {"physarum.sensorDistanceVariance", {0.0f, 20.0f}},
    {"physarum.sensorAngle",    {0.0f, 6.28f}},
    {"physarum.turningAngle",   {0.0f, 6.28f}},
    {"physarum.stepSize",       {0.1f, 100.0f}},
    {"physarum.levyAlpha",      {0.0f, 3.0f}},
    {"physarum.repulsionStrength", {0.0f, 1.0f}},
    {"physarum.samplingExponent", {0.0f, 10.0f}},
    {"physarum.gravityStrength", {0.0f, 1.0f}},
    {"physarum.orbitOffset",     {0.0f, 1.0f}},
    {"effects.blurScale",       {0.0f, 10.0f}},
    {"effects.chromaticOffset", {0.0f, 50.0f}},
    {"flowField.zoomBase",      {0.98f, 1.02f}},
    {"flowField.zoomRadial",    {-0.02f, 0.02f}},
    {"flowField.rotationSpeed",       {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"flowField.rotationSpeedRadial", {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"flowField.dxBase",        {-0.02f, 0.02f}},
    {"flowField.dxRadial",      {-0.02f, 0.02f}},
    {"flowField.dyBase",        {-0.02f, 0.02f}},
    {"flowField.dyRadial",      {-0.02f, 0.02f}},
    {"flowField.cx",            {0.0f, 1.0f}},
    {"flowField.cy",            {0.0f, 1.0f}},
    {"flowField.sx",            {0.9f, 1.1f}},
    {"flowField.sy",            {0.9f, 1.1f}},
    {"flowField.zoomAngular",   {-0.1f, 0.1f}},
    {"flowField.rotAngular",    {-ROTATION_OFFSET_MAX, ROTATION_OFFSET_MAX}},
    {"flowField.dxAngular",     {-0.02f, 0.02f}},
    {"flowField.dyAngular",     {-0.02f, 0.02f}},
    {"proceduralWarp.warp",     {0.0f, 2.0f}},
    {"proceduralWarp.warpSpeed", {0.1f, 2.0f}},
    {"proceduralWarp.warpScale", {0.1f, 100.0f}},
    {"feedbackFlow.strength",   {0.0f, 20.0f}},
    {"feedbackFlow.flowAngle",  {-ROTATION_OFFSET_MAX, ROTATION_OFFSET_MAX}},
    {"feedbackFlow.scale",      {1.0f, 5.0f}},
    {"feedbackFlow.threshold",  {0.0f, 0.1f}},
    {"voronoi.scale",                {5.0f, 50.0f}},
    {"voronoi.speed",                {0.1f, 2.0f}},
    {"voronoi.edgeFalloff",          {0.1f, 1.0f}},
    {"voronoi.isoFrequency",         {1.0f, 50.0f}},
    {"voronoi.uvDistortIntensity",   {0.0f, 1.0f}},
    {"voronoi.edgeIsoIntensity",     {0.0f, 1.0f}},
    {"voronoi.centerIsoIntensity",   {0.0f, 1.0f}},
    {"voronoi.flatFillIntensity",    {0.0f, 1.0f}},
    {"voronoi.organicFlowIntensity", {0.0f, 1.0f}},
    {"voronoi.edgeGlowIntensity",    {0.0f, 1.0f}},
    {"voronoi.determinantIntensity", {0.0f, 1.0f}},
    {"voronoi.ratioIntensity",       {0.0f, 1.0f}},
    {"voronoi.edgeDetectIntensity",  {0.0f, 1.0f}},
    {"kaleidoscope.rotationSpeed",    {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"kaleidoscope.twistAngle",       {-ROTATION_OFFSET_MAX, ROTATION_OFFSET_MAX}},
    {"kaleidoscope.smoothing",        {0.0f, 0.5f}},
    {"kifs.rotationSpeed",            {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"kifs.twistSpeed",               {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"kifs.polarFoldSmoothing",       {0.0f, 0.5f}},
    {"latticeFold.rotationSpeed",     {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"latticeFold.cellScale",         {1.0f, 20.0f}},
    {"latticeFold.smoothing",         {0.0f, 0.5f}},
    {"attractorFlow.rotationSpeedX",  {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"attractorFlow.rotationSpeedY",  {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"attractorFlow.rotationSpeedZ",  {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"attractorFlow.rotationAngleX",  {-ROTATION_OFFSET_MAX, ROTATION_OFFSET_MAX}},
    {"attractorFlow.rotationAngleY",  {-ROTATION_OFFSET_MAX, ROTATION_OFFSET_MAX}},
    {"attractorFlow.rotationAngleZ",  {-ROTATION_OFFSET_MAX, ROTATION_OFFSET_MAX}},
    {"sineWarp.strength",             {0.0f, 2.0f}},
    {"sineWarp.octaveRotation",       {-ROTATION_OFFSET_MAX, ROTATION_OFFSET_MAX}},
    {"infiniteZoom.spiralAngle",      {-ROTATION_OFFSET_MAX, ROTATION_OFFSET_MAX}},
    {"infiniteZoom.spiralTwist",      {-ROTATION_OFFSET_MAX, ROTATION_OFFSET_MAX}},
    {"textureWarp.strength",     {0.0f, 0.3f}},
    {"textureWarp.ridgeAngle",   {-ROTATION_OFFSET_MAX, ROTATION_OFFSET_MAX}},
    {"textureWarp.anisotropy",   {0.0f, 1.0f}},
    {"textureWarp.noiseAmount",  {0.0f, 1.0f}},
    {"waveRipple.strength",      {0.0f, 0.5f}},
    {"waveRipple.frequency",     {1.0f, 20.0f}},
    {"waveRipple.steepness",     {0.0f, 1.0f}},
    {"waveRipple.centerHole",    {0.0f, 0.5f}},
    {"waveRipple.originX",       {0.0f, 1.0f}},
    {"waveRipple.originY",       {0.0f, 1.0f}},
    {"waveRipple.shadeIntensity", {0.0f, 0.5f}},
    {"mobius.spiralTightness",   {-2.0f, 2.0f}},
    {"mobius.zoomFactor",        {-2.0f, 2.0f}},
    {"mobius.animRate",          {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"mobius.point1X",           {0.0f, 1.0f}},
    {"mobius.point1Y",           {0.0f, 1.0f}},
    {"mobius.point2X",           {0.0f, 1.0f}},
    {"mobius.point2Y",           {0.0f, 1.0f}},
    {"pixelation.cellCount",     {4.0f, 256.0f}},
    {"pixelation.ditherScale",   {1.0f, 8.0f}},
    {"glitch.analogIntensity",   {0.0f, 1.0f}},
    {"glitch.blockThreshold",    {0.0f, 0.9f}},
    {"glitch.aberration",        {0.0f, 20.0f}},
    {"glitch.blockOffset",       {0.0f, 0.5f}},
    {"poincareDisk.translationX",         {-0.9f, 0.9f}},
    {"poincareDisk.translationY",         {-0.9f, 0.9f}},
    {"poincareDisk.translationSpeed",     {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"poincareDisk.translationAmplitude", {0.0f, 0.9f}},
    {"poincareDisk.diskScale",            {0.5f, 2.0f}},
    {"poincareDisk.rotationSpeed",        {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"heightfieldRelief.lightAngle",      {0.0f, 6.28f}},
    {"heightfieldRelief.intensity",       {0.0f, 1.0f}},
    {"gradientFlow.strength",             {0.0f, 0.1f}},
    {"gradientFlow.edgeWeight",           {0.0f, 1.0f}},
    {"drosteZoom.scale",                  {1.5f, 10.0f}},
    {"drosteZoom.spiralAngle",            {-ROTATION_OFFSET_MAX, ROTATION_OFFSET_MAX}},
    {"drosteZoom.shearCoeff",             {-1.0f, 1.0f}},
    {"drosteZoom.innerRadius",            {0.0f, 0.5f}},
    {"colorGrade.hueShift",               {0.0f, 1.0f}},
    {"colorGrade.saturation",             {0.0f, 2.0f}},
    {"colorGrade.brightness",             {-2.0f, 2.0f}},
    {"colorGrade.contrast",               {0.5f, 2.0f}},
    {"colorGrade.temperature",            {-1.0f, 1.0f}},
    {"colorGrade.shadowsOffset",          {-0.5f, 0.5f}},
    {"colorGrade.midtonesOffset",         {-0.5f, 0.5f}},
    {"colorGrade.highlightsOffset",       {-0.5f, 0.5f}},
    {"asciiArt.cellSize",                 {4.0f, 32.0f}},
    {"oilPaint.radius",                   {2.0f, 8.0f}},
    {"watercolor.edgeDarkening",          {0.0f, 1.0f}},
    {"watercolor.granulationStrength",    {0.0f, 1.0f}},
    {"watercolor.bleedStrength",          {0.0f, 1.0f}},
    {"neonGlow.glowIntensity",            {0.5f, 5.0f}},
    {"neonGlow.edgeThreshold",            {0.0f, 0.5f}},
    {"neonGlow.originalVisibility",       {0.0f, 1.0f}},
    {"boids.cohesionWeight",              {0.0f, 2.0f}},
    {"boids.separationWeight",            {0.0f, 2.0f}},
    {"boids.alignmentWeight",             {0.0f, 2.0f}},
    {"radialPulse.radialFreq",            {1.0f, 30.0f}},
    {"radialPulse.radialAmp",             {-0.3f, 0.3f}},
    {"radialPulse.angularAmp",            {-0.5f, 0.5f}},
    {"radialPulse.petalAmp",              {-1.0f, 1.0f}},
    {"radialPulse.spiralTwist",           {-ROTATION_OFFSET_MAX, ROTATION_OFFSET_MAX}},
    {"falseColor.intensity",              {0.0f, 1.0f}},
    {"halftone.dotScale",                 {2.0f, 20.0f}},
    {"halftone.threshold",                {0.5f, 1.0f}},
    {"halftone.rotationSpeed",            {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"halftone.rotationAngle",            {-ROTATION_OFFSET_MAX, ROTATION_OFFSET_MAX}},
    {"curlAdvection.advectionCurl",       {0.0f, 1.0f}},
    {"curlAdvection.curlScale",           {-4.0f, 4.0f}},
    {"curlAdvection.selfAmp",             {0.5f, 2.0f}},
    {"curlAdvection.injectionIntensity",  {0.0f, 1.0f}},
    {"cymatics.waveScale",                {1.0f, 50.0f}},
    {"cymatics.falloff",                  {0.0f, 5.0f}},
    {"cymatics.visualGain",               {0.5f, 5.0f}},
    {"cymatics.boostIntensity",           {0.0f, 5.0f}},
    {"cymatics.baseRadius",               {0.0f, 0.5f}},
    {"cymatics.patternAngle",             {-ROTATION_OFFSET_MAX, ROTATION_OFFSET_MAX}},
    {"chladniWarp.n",                     {1.0f, 12.0f}},
    {"chladniWarp.m",                     {1.0f, 12.0f}},
    {"chladniWarp.strength",              {0.0f, 0.5f}},
    {"chladniWarp.animRange",             {0.0f, 5.0f}},
    {"crossHatching.width",               {0.5f, 4.0f}},
    {"crossHatching.threshold",           {0.0f, 2.0f}},
    {"crossHatching.noise",               {0.0f, 1.0f}},
    {"crossHatching.outline",             {0.0f, 1.0f}},
    {"paletteQuantization.colorLevels",   {2.0f, 16.0f}},
    {"paletteQuantization.ditherStrength", {0.0f, 1.0f}},
    {"bokeh.radius",                      {0.0f, 0.1f}},
    {"bokeh.brightnessPower",             {1.0f, 8.0f}},
    {"bloom.threshold",                   {0.0f, 2.0f}},
    {"bloom.intensity",                   {0.0f, 2.0f}},
    {"mandelbox.rotationSpeed",           {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"mandelbox.twistSpeed",              {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"mandelbox.boxIntensity",            {0.0f, 1.0f}},
    {"mandelbox.sphereIntensity",         {0.0f, 1.0f}},
    {"triangleFold.rotationSpeed",        {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"triangleFold.twistSpeed",           {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"domainWarp.warpStrength",           {0.0f, 0.5f}},
    {"domainWarp.falloff",                {0.3f, 0.8f}},
    {"domainWarp.driftSpeed",             {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"domainWarp.driftAngle",             {-ROTATION_OFFSET_MAX, ROTATION_OFFSET_MAX}},
    {"phyllotaxis.scale",                 {0.02f, 0.15f}},
    {"phyllotaxis.angleSpeed",            {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"phyllotaxis.phaseSpeed",            {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"phyllotaxis.cellRadius",            {0.1f, 1.5f}},
    {"phyllotaxis.isoFrequency",          {1.0f, 20.0f}},
    {"phyllotaxis.uvDistortIntensity",    {0.0f, 1.0f}},
    {"phyllotaxis.organicFlowIntensity",  {0.0f, 1.0f}},
    {"phyllotaxis.edgeIsoIntensity",      {0.0f, 1.0f}},
    {"phyllotaxis.centerIsoIntensity",    {0.0f, 1.0f}},
    {"phyllotaxis.flatFillIntensity",     {0.0f, 1.0f}},
    {"phyllotaxis.edgeGlowIntensity",     {0.0f, 1.0f}},
    {"phyllotaxis.ratioIntensity",        {0.0f, 1.0f}},
    {"phyllotaxis.determinantIntensity",  {0.0f, 1.0f}},
    {"phyllotaxis.edgeDetectIntensity",   {0.0f, 1.0f}},
    {"phyllotaxisWarp.warpStrength",      {0.0f, 1.0f}},
    {"phyllotaxisWarp.warpFalloff",       {1.0f, 20.0f}},
    {"phyllotaxisWarp.tangentIntensity",  {0.0f, 1.0f}},
    {"phyllotaxisWarp.radialIntensity",   {0.0f, 1.0f}},
    {"phyllotaxisWarp.spinSpeed",         {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"densityWaveSpiral.tightness",            {-3.14159f, 3.14159f}},
    {"densityWaveSpiral.rotationSpeed",        {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"densityWaveSpiral.globalRotationSpeed",  {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"densityWaveSpiral.thickness",            {0.05f, 0.5f}},
    {"moireInterference.rotationAngle",        {-ROTATION_OFFSET_MAX, ROTATION_OFFSET_MAX}},
    {"moireInterference.scaleDiff",            {0.5f, 2.0f}},
    {"moireInterference.animationSpeed",       {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"pencilSketch.strokeFalloff",             {0.0f, 1.0f}},
    {"pencilSketch.paperStrength",             {0.0f, 1.0f}},
    {"pencilSketch.vignetteStrength",          {0.0f, 1.0f}},
    {"pencilSketch.wobbleAmount",              {0.0f, 8.0f}},
};

static const int PARAM_COUNT = sizeof(PARAM_TABLE) / sizeof(PARAM_TABLE[0]);

// Drawable field bounds: matched by field name in "drawable.<id>.<field>"
static const ParamEntry DRAWABLE_FIELD_TABLE[] = {
    {"x",              {-1.0f, 2.0f}},
    {"y",              {-1.0f, 2.0f}},
    {"rotationSpeed",  {-ROTATION_SPEED_MAX, ROTATION_SPEED_MAX}},
    {"rotationAngle",  {-ROTATION_OFFSET_MAX, ROTATION_OFFSET_MAX}},
    {"texAngle",       {-ROTATION_OFFSET_MAX, ROTATION_OFFSET_MAX}},
    {"width",          {0.01f, 2.0f}},
    {"height",         {0.01f, 2.0f}},
};

static const int DRAWABLE_FIELD_COUNT = sizeof(DRAWABLE_FIELD_TABLE) / sizeof(DRAWABLE_FIELD_TABLE[0]);

void ParamRegistryInit(EffectConfig* effects)
{
    float* targets[] = {
        &effects->physarum.sensorDistance,
        &effects->physarum.sensorDistanceVariance,
        &effects->physarum.sensorAngle,
        &effects->physarum.turningAngle,
        &effects->physarum.stepSize,
        &effects->physarum.levyAlpha,
        &effects->physarum.repulsionStrength,
        &effects->physarum.samplingExponent,
        &effects->physarum.gravityStrength,
        &effects->physarum.orbitOffset,
        &effects->blurScale,
        &effects->chromaticOffset,
        &effects->flowField.zoomBase,
        &effects->flowField.zoomRadial,
        &effects->flowField.rotationSpeed,
        &effects->flowField.rotationSpeedRadial,
        &effects->flowField.dxBase,
        &effects->flowField.dxRadial,
        &effects->flowField.dyBase,
        &effects->flowField.dyRadial,
        &effects->flowField.cx,
        &effects->flowField.cy,
        &effects->flowField.sx,
        &effects->flowField.sy,
        &effects->flowField.zoomAngular,
        &effects->flowField.rotAngular,
        &effects->flowField.dxAngular,
        &effects->flowField.dyAngular,
        &effects->proceduralWarp.warp,
        &effects->proceduralWarp.warpSpeed,
        &effects->proceduralWarp.warpScale,
        &effects->feedbackFlow.strength,
        &effects->feedbackFlow.flowAngle,
        &effects->feedbackFlow.scale,
        &effects->feedbackFlow.threshold,
        &effects->voronoi.scale,
        &effects->voronoi.speed,
        &effects->voronoi.edgeFalloff,
        &effects->voronoi.isoFrequency,
        &effects->voronoi.uvDistortIntensity,
        &effects->voronoi.edgeIsoIntensity,
        &effects->voronoi.centerIsoIntensity,
        &effects->voronoi.flatFillIntensity,
        &effects->voronoi.organicFlowIntensity,
        &effects->voronoi.edgeGlowIntensity,
        &effects->voronoi.determinantIntensity,
        &effects->voronoi.ratioIntensity,
        &effects->voronoi.edgeDetectIntensity,
        &effects->kaleidoscope.rotationSpeed,
        &effects->kaleidoscope.twistAngle,
        &effects->kaleidoscope.smoothing,
        &effects->kifs.rotationSpeed,
        &effects->kifs.twistSpeed,
        &effects->kifs.polarFoldSmoothing,
        &effects->latticeFold.rotationSpeed,
        &effects->latticeFold.cellScale,
        &effects->latticeFold.smoothing,
        &effects->attractorFlow.rotationSpeedX,
        &effects->attractorFlow.rotationSpeedY,
        &effects->attractorFlow.rotationSpeedZ,
        &effects->attractorFlow.rotationAngleX,
        &effects->attractorFlow.rotationAngleY,
        &effects->attractorFlow.rotationAngleZ,
        &effects->sineWarp.strength,
        &effects->sineWarp.octaveRotation,
        &effects->infiniteZoom.spiralAngle,
        &effects->infiniteZoom.spiralTwist,
        &effects->textureWarp.strength,
        &effects->textureWarp.ridgeAngle,
        &effects->textureWarp.anisotropy,
        &effects->textureWarp.noiseAmount,
        &effects->waveRipple.strength,
        &effects->waveRipple.frequency,
        &effects->waveRipple.steepness,
        &effects->waveRipple.centerHole,
        &effects->waveRipple.originX,
        &effects->waveRipple.originY,
        &effects->waveRipple.shadeIntensity,
        &effects->mobius.spiralTightness,
        &effects->mobius.zoomFactor,
        &effects->mobius.animRate,
        &effects->mobius.point1X,
        &effects->mobius.point1Y,
        &effects->mobius.point2X,
        &effects->mobius.point2Y,
        &effects->pixelation.cellCount,
        &effects->pixelation.ditherScale,
        &effects->glitch.analogIntensity,
        &effects->glitch.blockThreshold,
        &effects->glitch.aberration,
        &effects->glitch.blockOffset,
        &effects->poincareDisk.translationX,
        &effects->poincareDisk.translationY,
        &effects->poincareDisk.translationSpeed,
        &effects->poincareDisk.translationAmplitude,
        &effects->poincareDisk.diskScale,
        &effects->poincareDisk.rotationSpeed,
        &effects->heightfieldRelief.lightAngle,
        &effects->heightfieldRelief.intensity,
        &effects->gradientFlow.strength,
        &effects->gradientFlow.edgeWeight,
        &effects->drosteZoom.scale,
        &effects->drosteZoom.spiralAngle,
        &effects->drosteZoom.shearCoeff,
        &effects->drosteZoom.innerRadius,
        &effects->colorGrade.hueShift,
        &effects->colorGrade.saturation,
        &effects->colorGrade.brightness,
        &effects->colorGrade.contrast,
        &effects->colorGrade.temperature,
        &effects->colorGrade.shadowsOffset,
        &effects->colorGrade.midtonesOffset,
        &effects->colorGrade.highlightsOffset,
        &effects->asciiArt.cellSize,
        &effects->oilPaint.radius,
        &effects->watercolor.edgeDarkening,
        &effects->watercolor.granulationStrength,
        &effects->watercolor.bleedStrength,
        &effects->neonGlow.glowIntensity,
        &effects->neonGlow.edgeThreshold,
        &effects->neonGlow.originalVisibility,
        &effects->boids.cohesionWeight,
        &effects->boids.separationWeight,
        &effects->boids.alignmentWeight,
        &effects->radialPulse.radialFreq,
        &effects->radialPulse.radialAmp,
        &effects->radialPulse.angularAmp,
        &effects->radialPulse.petalAmp,
        &effects->radialPulse.spiralTwist,
        &effects->falseColor.intensity,
        &effects->halftone.dotScale,
        &effects->halftone.threshold,
        &effects->halftone.rotationSpeed,
        &effects->halftone.rotationAngle,
        &effects->curlAdvection.advectionCurl,
        &effects->curlAdvection.curlScale,
        &effects->curlAdvection.selfAmp,
        &effects->curlAdvection.injectionIntensity,
        &effects->cymatics.waveScale,
        &effects->cymatics.falloff,
        &effects->cymatics.visualGain,
        &effects->cymatics.boostIntensity,
        &effects->cymatics.baseRadius,
        &effects->cymatics.patternAngle,
        &effects->chladniWarp.n,
        &effects->chladniWarp.m,
        &effects->chladniWarp.strength,
        &effects->chladniWarp.animRange,
        &effects->crossHatching.width,
        &effects->crossHatching.threshold,
        &effects->crossHatching.noise,
        &effects->crossHatching.outline,
        &effects->paletteQuantization.colorLevels,
        &effects->paletteQuantization.ditherStrength,
        &effects->bokeh.radius,
        &effects->bokeh.brightnessPower,
        &effects->bloom.threshold,
        &effects->bloom.intensity,
        &effects->mandelbox.rotationSpeed,
        &effects->mandelbox.twistSpeed,
        &effects->mandelbox.boxIntensity,
        &effects->mandelbox.sphereIntensity,
        &effects->triangleFold.rotationSpeed,
        &effects->triangleFold.twistSpeed,
        &effects->domainWarp.warpStrength,
        &effects->domainWarp.falloff,
        &effects->domainWarp.driftSpeed,
        &effects->domainWarp.driftAngle,
        &effects->phyllotaxis.scale,
        &effects->phyllotaxis.angleSpeed,
        &effects->phyllotaxis.phaseSpeed,
        &effects->phyllotaxis.cellRadius,
        &effects->phyllotaxis.isoFrequency,
        &effects->phyllotaxis.uvDistortIntensity,
        &effects->phyllotaxis.organicFlowIntensity,
        &effects->phyllotaxis.edgeIsoIntensity,
        &effects->phyllotaxis.centerIsoIntensity,
        &effects->phyllotaxis.flatFillIntensity,
        &effects->phyllotaxis.edgeGlowIntensity,
        &effects->phyllotaxis.ratioIntensity,
        &effects->phyllotaxis.determinantIntensity,
        &effects->phyllotaxis.edgeDetectIntensity,
        &effects->phyllotaxisWarp.warpStrength,
        &effects->phyllotaxisWarp.warpFalloff,
        &effects->phyllotaxisWarp.tangentIntensity,
        &effects->phyllotaxisWarp.radialIntensity,
        &effects->phyllotaxisWarp.spinSpeed,
        &effects->densityWaveSpiral.tightness,
        &effects->densityWaveSpiral.rotationSpeed,
        &effects->densityWaveSpiral.globalRotationSpeed,
        &effects->densityWaveSpiral.thickness,
        &effects->moireInterference.rotationAngle,
        &effects->moireInterference.scaleDiff,
        &effects->moireInterference.animationSpeed,
        &effects->pencilSketch.strokeFalloff,
        &effects->pencilSketch.paperStrength,
        &effects->pencilSketch.vignetteStrength,
        &effects->pencilSketch.wobbleAmount,
    };

    for (int i = 0; i < PARAM_COUNT; i++) {
        ModEngineRegisterParam(PARAM_TABLE[i].id, targets[i],
                               PARAM_TABLE[i].def.min, PARAM_TABLE[i].def.max);
    }
}

const ParamDef* ParamRegistryGet(const char* paramId)
{
    for (int i = 0; i < PARAM_COUNT; i++) {
        if (strcmp(PARAM_TABLE[i].id, paramId) == 0) {
            return &PARAM_TABLE[i].def;
        }
    }
    return NULL;
}

bool ParamRegistryGetDynamic(const char* paramId, ParamDef* outDef)
{
    // Check static table first
    const ParamDef* staticDef = ParamRegistryGet(paramId);
    if (staticDef != NULL) {
        *outDef = *staticDef;
        return true;
    }

    // Match drawable.<id>.<field> pattern
    if (strncmp(paramId, "drawable.", 9) == 0) {
        const char* afterPrefix = paramId + 9;
        const char* dot = strchr(afterPrefix, '.');
        if (dot != NULL) {
            const char* fieldName = dot + 1;
            for (int i = 0; i < DRAWABLE_FIELD_COUNT; i++) {
                if (strcmp(DRAWABLE_FIELD_TABLE[i].id, fieldName) == 0) {
                    *outDef = DRAWABLE_FIELD_TABLE[i].def;
                    return true;
                }
            }
        }
    }

    // Match lfo<n>.rate pattern (registered separately via ModEngineRegisterParam)
    if (strncmp(paramId, "lfo", 3) == 0 && strstr(paramId, ".rate") != NULL) {
        outDef->min = LFO_RATE_MIN;
        outDef->max = LFO_RATE_MAX;
        return true;
    }

    return false;
}
