#ifndef POST_EFFECT_H
#define POST_EFFECT_H

#include <stdint.h>
#include "raylib.h"
#include "config/effect_config.h"

typedef struct Physarum Physarum;
typedef struct CurlFlow CurlFlow;
typedef struct CurlAdvection CurlAdvection;
typedef struct AttractorFlow AttractorFlow;
typedef struct Boids Boids;
typedef struct Cymatics Cymatics;
typedef struct BlendCompositor BlendCompositor;
typedef struct ColorLUT ColorLUT;

typedef struct PostEffect {
    RenderTexture2D accumTexture;     // Feedback buffer (persists between frames)
    RenderTexture2D pingPong[2];      // Ping-pong buffers for multi-pass effects
    RenderTexture2D outputTexture;    // Previous frame's final output (1-frame delay) for textured shapes
    Shader feedbackShader;
    Shader blurHShader;
    Shader blurVShader;
    Shader chromaticShader;
    Shader kaleidoShader;
    Shader voronoiShader;
    Shader fxaaShader;
    Shader clarityShader;
    Shader gammaShader;
    Shader shapeTextureShader;
    Shader infiniteZoomShader;
    Shader sineWarpShader;
    Shader radialStreakShader;
    Shader textureWarpShader;
    Shader waveRippleShader;
    Shader mobiusShader;
    Shader pixelationShader;
    Shader glitchShader;
    Shader poincareDiskShader;
    Shader toonShader;
    Shader heightfieldReliefShader;
    Shader gradientFlowShader;
    Shader drosteZoomShader;
    Shader kifsShader;
    Shader latticeFoldShader;
    Shader colorGradeShader;
    Shader asciiArtShader;
    Shader oilPaintShader;
    Shader watercolorShader;
    Shader neonGlowShader;
    Shader radialPulseShader;
    Shader falseColorShader;
    Shader halftoneShader;
    Shader chladniWarpShader;
    Shader crossHatchingShader;
    Shader paletteQuantizationShader;
    Shader bokehShader;
    Shader bloomPrefilterShader;
    Shader bloomDownsampleShader;
    Shader bloomUpsampleShader;
    Shader bloomCompositeShader;
    Shader mandelboxShader;
    Shader triangleFoldShader;
    Shader domainWarpShader;
    Shader phyllotaxisShader;
    Shader phyllotaxisWarpShader;
    RenderTexture2D bloomMips[BLOOM_MIP_COUNT];
    int shapeTexZoomLoc;
    int shapeTexAngleLoc;
    int shapeTexBrightnessLoc;
    int blurHResolutionLoc;
    int blurVResolutionLoc;
    int blurHScaleLoc;
    int blurVScaleLoc;
    int halfLifeLoc;
    int deltaTimeLoc;
    int chromaticResolutionLoc;
    int chromaticOffsetLoc;
    int kaleidoSegmentsLoc;
    int kaleidoRotationLoc;
    int kaleidoTwistLoc;
    int kaleidoSmoothingLoc;
    int kifsRotationLoc;
    int kifsTwistLoc;
    int kifsIterationsLoc;
    int kifsScaleLoc;
    int kifsOffsetLoc;
    int kifsOctantFoldLoc;
    int kifsPolarFoldLoc;
    int kifsPolarFoldSegmentsLoc;
    int kifsPolarFoldSmoothingLoc;
    int latticeFoldCellTypeLoc;
    int latticeFoldCellScaleLoc;
    int latticeFoldRotationLoc;
    int latticeFoldTimeLoc;
    int latticeFoldSmoothingLoc;
    int voronoiResolutionLoc;
    int voronoiScaleLoc;
    int voronoiTimeLoc;
    int voronoiEdgeFalloffLoc;
    int voronoiIsoFrequencyLoc;
    int voronoiSmoothModeLoc;
    int voronoiUvDistortIntensityLoc;
    int voronoiEdgeIsoIntensityLoc;
    int voronoiCenterIsoIntensityLoc;
    int voronoiFlatFillIntensityLoc;
    int voronoiOrganicFlowIntensityLoc;
    int voronoiEdgeGlowIntensityLoc;
    int voronoiDeterminantIntensityLoc;
    int voronoiRatioIntensityLoc;
    int voronoiEdgeDetectIntensityLoc;
    int feedbackResolutionLoc;
    int feedbackDesaturateLoc;
    int feedbackZoomBaseLoc;
    int feedbackZoomRadialLoc;
    int feedbackRotBaseLoc;
    int feedbackRotRadialLoc;
    int feedbackDxBaseLoc;
    int feedbackDxRadialLoc;
    int feedbackDyBaseLoc;
    int feedbackDyRadialLoc;
    int feedbackFlowStrengthLoc;
    int feedbackFlowAngleLoc;
    int feedbackFlowScaleLoc;
    int feedbackFlowThresholdLoc;
    int feedbackCxLoc;
    int feedbackCyLoc;
    int feedbackSxLoc;
    int feedbackSyLoc;
    int feedbackZoomAngularLoc;
    int feedbackZoomAngularFreqLoc;
    int feedbackRotAngularLoc;
    int feedbackRotAngularFreqLoc;
    int feedbackDxAngularLoc;
    int feedbackDxAngularFreqLoc;
    int feedbackDyAngularLoc;
    int feedbackDyAngularFreqLoc;
    int feedbackWarpLoc;
    int feedbackWarpTimeLoc;
    int feedbackWarpScaleInverseLoc;
    int fxaaResolutionLoc;
    int clarityResolutionLoc;
    int clarityAmountLoc;
    int gammaGammaLoc;
    int infiniteZoomTimeLoc;
    int infiniteZoomZoomDepthLoc;
    int infiniteZoomLayersLoc;
    int infiniteZoomSpiralAngleLoc;
    int infiniteZoomSpiralTwistLoc;
    int sineWarpTimeLoc;
    int sineWarpOctavesLoc;
    int sineWarpStrengthLoc;
    int sineWarpOctaveRotationLoc;
    int radialStreakSamplesLoc;
    int radialStreakStreakLengthLoc;
    int textureWarpStrengthLoc;
    int textureWarpIterationsLoc;
    int textureWarpChannelModeLoc;
    int textureWarpRidgeAngleLoc;
    int textureWarpAnisotropyLoc;
    int textureWarpNoiseAmountLoc;
    int textureWarpNoiseScaleLoc;
    int waveRippleTimeLoc;
    int waveRippleOctavesLoc;
    int waveRippleStrengthLoc;
    int waveRippleFrequencyLoc;
    int waveRippleSteepnessLoc;
    int waveRippleCenterHoleLoc;
    int waveRippleOriginLoc;
    int waveRippleShadeEnabledLoc;
    int waveRippleShadeIntensityLoc;
    int mobiusTimeLoc;
    int mobiusPoint1Loc;
    int mobiusPoint2Loc;
    int mobiusSpiralTightnessLoc;
    int mobiusZoomFactorLoc;
    int pixelationResolutionLoc;
    int pixelationCellCountLoc;
    int pixelationDitherScaleLoc;
    int pixelationPosterizeLevelsLoc;
    int glitchResolutionLoc;
    int glitchTimeLoc;
    int glitchFrameLoc;
    int glitchCrtEnabledLoc;
    int glitchCurvatureLoc;
    int glitchVignetteEnabledLoc;
    int glitchAnalogIntensityLoc;
    int glitchAberrationLoc;
    int glitchBlockThresholdLoc;
    int glitchBlockOffsetLoc;
    int glitchVhsEnabledLoc;
    int glitchTrackingBarIntensityLoc;
    int glitchScanlineNoiseIntensityLoc;
    int glitchColorDriftIntensityLoc;
    int glitchScanlineAmountLoc;
    int glitchNoiseAmountLoc;
    int poincareDiskTilePLoc;
    int poincareDiskTileQLoc;
    int poincareDiskTileRLoc;
    int poincareDiskTranslationLoc;
    int poincareDiskRotationLoc;
    int poincareDiskDiskScaleLoc;
    int toonResolutionLoc;
    int toonLevelsLoc;
    int toonEdgeThresholdLoc;
    int toonEdgeSoftnessLoc;
    int toonThicknessVariationLoc;
    int toonNoiseScaleLoc;
    int heightfieldReliefResolutionLoc;
    int heightfieldReliefIntensityLoc;
    int heightfieldReliefReliefScaleLoc;
    int heightfieldReliefLightAngleLoc;
    int heightfieldReliefLightHeightLoc;
    int heightfieldReliefShininessLoc;
    int gradientFlowResolutionLoc;
    int gradientFlowStrengthLoc;
    int gradientFlowIterationsLoc;
    int gradientFlowFlowAngleLoc;
    int gradientFlowEdgeWeightLoc;
    int drosteZoomTimeLoc;
    int drosteZoomScaleLoc;
    int drosteZoomSpiralAngleLoc;
    int drosteZoomShearCoeffLoc;
    int drosteZoomInnerRadiusLoc;
    int drosteZoomBranchesLoc;
    int colorGradeHueShiftLoc;
    int colorGradeSaturationLoc;
    int colorGradeBrightnessLoc;
    int colorGradeContrastLoc;
    int colorGradeTemperatureLoc;
    int colorGradeShadowsOffsetLoc;
    int colorGradeMidtonesOffsetLoc;
    int colorGradeHighlightsOffsetLoc;
    int asciiArtResolutionLoc;
    int asciiArtCellPixelsLoc;
    int asciiArtColorModeLoc;
    int asciiArtForegroundLoc;
    int asciiArtBackgroundLoc;
    int asciiArtInvertLoc;
    int oilPaintResolutionLoc;
    int oilPaintRadiusLoc;
    int watercolorResolutionLoc;
    int watercolorEdgeDarkeningLoc;
    int watercolorGranulationStrengthLoc;
    int watercolorPaperScaleLoc;
    int watercolorSoftnessLoc;
    int watercolorBleedStrengthLoc;
    int watercolorBleedRadiusLoc;
    int watercolorColorLevelsLoc;
    int neonGlowResolutionLoc;
    int neonGlowGlowColorLoc;
    int neonGlowEdgeThresholdLoc;
    int neonGlowEdgePowerLoc;
    int neonGlowGlowIntensityLoc;
    int neonGlowGlowRadiusLoc;
    int neonGlowGlowSamplesLoc;
    int neonGlowOriginalVisibilityLoc;
    int radialPulseRadialFreqLoc;
    int radialPulseRadialAmpLoc;
    int radialPulseSegmentsLoc;
    int radialPulseAngularAmpLoc;
    int radialPulsePetalAmpLoc;
    int radialPulsePhaseLoc;
    int radialPulseSpiralTwistLoc;
    int falseColorIntensityLoc;
    int falseColorGradientLUTLoc;
    int halftoneResolutionLoc;
    int halftoneDotScaleLoc;
    int halftoneDotSizeLoc;
    int halftoneRotationLoc;
    int halftoneThresholdLoc;
    int halftoneSoftnessLoc;
    int chladniWarpNLoc;
    int chladniWarpMLoc;
    int chladniWarpPlateSizeLoc;
    int chladniWarpStrengthLoc;
    int chladniWarpModeLoc;
    int chladniWarpAnimPhaseLoc;
    int chladniWarpAnimRangeLoc;
    int chladniWarpPreFoldLoc;
    int crossHatchingResolutionLoc;
    int crossHatchingTimeLoc;
    int crossHatchingWidthLoc;
    int crossHatchingThresholdLoc;
    int crossHatchingNoiseLoc;
    int crossHatchingOutlineLoc;
    int paletteQuantizationColorLevelsLoc;
    int paletteQuantizationDitherStrengthLoc;
    int paletteQuantizationBayerSizeLoc;
    int bokehResolutionLoc;
    int bokehRadiusLoc;
    int bokehIterationsLoc;
    int bokehBrightnessPowerLoc;
    int bloomThresholdLoc;
    int bloomKneeLoc;
    int bloomDownsampleHalfpixelLoc;
    int bloomUpsampleHalfpixelLoc;
    int bloomIntensityLoc;
    int bloomBloomTexLoc;
    int mandelboxIterationsLoc;
    int mandelboxBoxLimitLoc;
    int mandelboxSphereMinLoc;
    int mandelboxSphereMaxLoc;
    int mandelboxScaleLoc;
    int mandelboxOffsetLoc;
    int mandelboxRotationLoc;
    int mandelboxTwistAngleLoc;
    int mandelboxBoxIntensityLoc;
    int mandelboxSphereIntensityLoc;
    int mandelboxPolarFoldLoc;
    int mandelboxPolarFoldSegmentsLoc;
    int triangleFoldIterationsLoc;
    int triangleFoldScaleLoc;
    int triangleFoldOffsetLoc;
    int triangleFoldRotationLoc;
    int triangleFoldTwistAngleLoc;
    int domainWarpWarpStrengthLoc;
    int domainWarpWarpScaleLoc;
    int domainWarpWarpIterationsLoc;
    int domainWarpFalloffLoc;
    int domainWarpTimeOffsetLoc;
    int phyllotaxisResolutionLoc;
    int phyllotaxisScaleLoc;
    int phyllotaxisDivergenceAngleLoc;
    int phyllotaxisPhaseTimeLoc;
    int phyllotaxisCellRadiusLoc;
    int phyllotaxisIsoFrequencyLoc;
    int phyllotaxisUvDistortIntensityLoc;
    int phyllotaxisOrganicFlowIntensityLoc;
    int phyllotaxisEdgeIsoIntensityLoc;
    int phyllotaxisCenterIsoIntensityLoc;
    int phyllotaxisFlatFillIntensityLoc;
    int phyllotaxisEdgeGlowIntensityLoc;
    int phyllotaxisRatioIntensityLoc;
    int phyllotaxisDeterminantIntensityLoc;
    int phyllotaxisEdgeDetectIntensityLoc;
    int phyllotaxisWarpScaleLoc;
    int phyllotaxisWarpDivergenceAngleLoc;
    int phyllotaxisWarpWarpStrengthLoc;
    int phyllotaxisWarpWarpFalloffLoc;
    int phyllotaxisWarpTangentIntensityLoc;
    int phyllotaxisWarpRadialIntensityLoc;
    int phyllotaxisWarpSpinOffsetLoc;
    EffectConfig effects;
    int screenWidth;
    int screenHeight;
    float voronoiTime;
    Physarum* physarum;
    CurlFlow* curlFlow;
    CurlAdvection* curlAdvection;
    AttractorFlow* attractorFlow;
    Boids* boids;
    Cymatics* cymatics;
    BlendCompositor* blendCompositor;
    ColorLUT* falseColorLUT;    // 1D gradient texture for false color effect
    Texture2D fftTexture;       // 1D texture (1025x1) for normalized FFT magnitudes
    float fftMaxMagnitude;      // Running max for auto-normalization
    Texture2D waveformTexture;  // 1D texture (2048x1) for waveform history ring buffer
    // Temporaries for RenderPass callbacks
    float currentDeltaTime;
    float currentBlurScale;
    float currentKaleidoRotation;
    float transformTime;  // Shared animation time for transform effects
    float currentKifsRotation;
    float currentKifsTwist;
    float currentLatticeFoldRotation;
    float infiniteZoomTime;
    float sineWarpTime;
    float waveRippleTime;
    float currentWaveRippleOrigin[2];
    float mobiusTime;
    float currentMobiusPoint1[2];
    float currentMobiusPoint2[2];
    float glitchTime;
    int glitchFrame;
    float poincareTime;
    float currentPoincareTranslation[2];
    float currentPoincareRotation;
    float drosteZoomTime;
    float radialPulseTime;
    float currentHalftoneRotation;
    float warpTime;
    float chladniWarpPhase;
    float crossHatchingTime;
    float currentMandelboxRotation;
    float currentMandelboxTwist;
    float currentTriangleFoldRotation;
    float currentTriangleFoldTwist;
    float domainWarpDrift;
    float phyllotaxisAngleTime;
    float phyllotaxisPhaseTime;
    float phyllotaxisWarpSpinOffset;
    // Trail boost active state (computed per-frame in RenderPipelineApplyOutput)
    bool physarumBoostActive;
    bool curlFlowBoostActive;
    bool curlAdvectionBoostActive;
    bool attractorFlowBoostActive;
    bool boidsBoostActive;
    bool cymaticsBoostActive;
} PostEffect;

// Initialize post-effect processor with screen dimensions
// Loads shaders and creates accumulation texture
// Returns NULL on failure
PostEffect* PostEffectInit(int screenWidth, int screenHeight);

// Clean up post-effect resources
void PostEffectUninit(PostEffect* pe);

// Resize render textures (call when window resizes)
void PostEffectResize(PostEffect* pe, int width, int height);

// Clear feedback buffers and reset simulations (call when switching presets)
void PostEffectClearFeedback(PostEffect* pe);

// Begin drawing waveforms to accumulation texture
void PostEffectBeginDrawStage(PostEffect* pe);

// End drawing waveforms to accumulation texture
void PostEffectEndDrawStage(void);

#endif // POST_EFFECT_H
