#ifndef ATTRACTOR_TYPES_H
#define ATTRACTOR_TYPES_H

typedef enum AttractorType {
  ATTRACTOR_LORENZ = 0,
  ATTRACTOR_ROSSLER,
  ATTRACTOR_AIZAWA,
  ATTRACTOR_THOMAS,
  ATTRACTOR_DADRAS,
  ATTRACTOR_CHUA,
  ATTRACTOR_COUNT
} AttractorType;

#endif // ATTRACTOR_TYPES_H
